baseURL = "https://augustinechiajh.github.io/"
languageCode = "en-us"
title = "Your Name - Resume"
theme = "PaperMod"

[params]
  author = "Your Name"
  description = "My personal resume site"
  ShowBreadCrumbs = false
  ShowReadingTime = false
  ShowPostNavLinks = false
  ShowToc = false

[params.homeInfoParams]
  Title = "👋 Hello"
  Content = "I'm a Cloud & DevOps Engineer passionate about automation and infrastructure."

[[menu.main]]
  name = "Resume"
  url = "/resume"
  weight = 1

# [[params.socialIcons]]
#   name = "github"
#   url = "https://github.com/yourusername"

# [[params.socialIcons]]
#   name = "linkedin"
#   url = "https://linkedin.com/in/yourusername"
