baseURL = 'https://augustinechiajh.github.io/resume-site/'
languageCode = 'en-us'
title = 'Your Name - Resume'
theme = 'PaperMod'
publishDir = 'public'

[[menu.main]]
  name = "Resume"
  url = "/resume"
  weight = 1